#! /bin/sh

cproto -I. -I.. $(grep '^GCSRC' Makefile.am | sed 's/GCSRC *= *//') | grep -v WinMain | sed 's/\(AboutDlgProc\|WndProc\|OptDlgProc\|RenameLblProc\)/CALLBACK &/' | sed 's/\(OnOptDlgInit\)/WINAPI &/'
